# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=bandit
    - python: 3.6
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=readme
    - python: 3.6
      env: TOX_ENV=manifest
    - python: 3.6
      env: TOX_ENV=py36

install:
  - pip install tox
  - pip install codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov

# The Travis cache is used to speed up dependency installation
# by caching Pip downloads. Pip's logfile is removed to prevent
# timestamps from causing false positive cache misses.
before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
